name: Norm and Valgrind

on:
  push:
    branches:
      - main
      - master

jobs:
  valgrind-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential valgrind

    - name: Build Project
      run: make

    - name: Run Valgrind
      run: valgrind --leak-check=full ./push_swap 5 4 3 2 1

  norminette:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install norminette==3.3.40
    - name: Lint with norminette
      run: |
        norminette
